CC=gcc
CFLAGS=-Wall -std=c11
 
construct_3_structs_add: snode.h construct_3_structs_add.c
	$(CC) $(CFLAGS) construct_3_structs_add.c -o construct_3_structs_add
clean:
	rm -f *.o construct_3_structs_add
