CC=gcc
CFLAGS=-Wall -std=c11
 
construct_3_structs_delete: snode.h construct_3_structs_delete.c
	$(CC) $(CFLAGS) construct_3_structs_delete.c -o construct_3_structs_delete
clean:
	rm -f *.o construct_3_structs_delete
